// Code generated by sqlc. DO NOT EDIT.
// source: notice.sql

package model

import (
	"context"
)

const countAllClothes = `-- name: CountAllClothes :one
SELECT count(nco.id)
FROM nc_core_closet nco
WHERE nco.del_flag=false AND nco.use_flag=true
`

func (q *Queries) CountAllClothes(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAllClothes)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAllOutfits = `-- name: CountAllOutfits :one
SELECT count(nco.id)
FROM nc_core_outfit nco
WHERE nco.del_flag=false AND nco.use_flag=true
`

func (q *Queries) CountAllOutfits(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAllOutfits)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAllPosts = `-- name: CountAllPosts :one
SELECT count(post.post_id)
FROM post
WHERE post.is_delete=false
`

func (q *Queries) CountAllPosts(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAllPosts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAllSchedules = `-- name: CountAllSchedules :one
SELECT count(nus.id)
FROM nc_usr_schedule nus
WHERE nus.del_flag=false AND nus.use_flag=true
`

func (q *Queries) CountAllSchedules(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAllSchedules)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAllUsers = `-- name: CountAllUsers :one
SELECT count(nua.id)
FROM nc_usr_account nua
WHERE nua.del_flag=false
`

func (q *Queries) CountAllUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAllUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRecentRegisteredClothes = `-- name: CountRecentRegisteredClothes :one
SELECT count(nco.id)
FROM nc_core_closet nco
WHERE nco.del_flag=false AND nco.use_flag=true AND nco.create_dt>(now() - interval '7 day')
`

func (q *Queries) CountRecentRegisteredClothes(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentRegisteredClothes)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRecentRegisteredOutfits = `-- name: CountRecentRegisteredOutfits :one

SELECT count(nco.id)
FROM nc_core_outfit nco
WHERE nco.del_flag=false AND nco.use_flag=true AND nco.create_dt>(now() - interval '7 day')
`

func (q *Queries) CountRecentRegisteredOutfits(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentRegisteredOutfits)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRecentRegisteredPosts = `-- name: CountRecentRegisteredPosts :one
SELECT count(post.post_id)
FROM post
WHERE post.is_delete=false AND post.create_date>(now() - interval '7 day')
`

func (q *Queries) CountRecentRegisteredPosts(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentRegisteredPosts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRecentRegisteredUsers = `-- name: CountRecentRegisteredUsers :one
SELECT count(nua.id)
FROM nc_usr_account nua
WHERE nua.del_flag=false AND nua.create_dt>(now() - interval '7 day')
`

func (q *Queries) CountRecentRegisteredUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentRegisteredUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRecentSchedules = `-- name: CountRecentSchedules :one
SELECT count(nus.id)
FROM nc_usr_schedule nus
WHERE nus.del_flag=false AND nus.use_flag=true AND nus.create_dt>(now() - interval '7 day')
`

func (q *Queries) CountRecentSchedules(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentSchedules)
	var count int64
	err := row.Scan(&count)
	return count, err
}
