// Code generated by sqlc. DO NOT EDIT.

package model

import (
	"context"
)

type Querier interface {
	CountAllClothes(ctx context.Context) (int64, error)
	CountAllOutfits(ctx context.Context) (int64, error)
	CountAllPosts(ctx context.Context) (int64, error)
	CountAllSchedules(ctx context.Context) (int64, error)
	CountAllUsers(ctx context.Context) (int64, error)
	CountRecentRegisteredClothes(ctx context.Context) (int64, error)
	CountRecentRegisteredOutfits(ctx context.Context) (int64, error)
	CountRecentRegisteredPosts(ctx context.Context) (int64, error)
	CountRecentRegisteredUsers(ctx context.Context) (int64, error)
	CountRecentSchedules(ctx context.Context) (int64, error)
}

var _ Querier = (*Queries)(nil)
